services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=api-notas-fiscais'
      - 'POSTGRES_PASSWORD=sa'
      - 'POSTGRES_USER=sa'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'


volumes:
  postgres-data:
